AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false